version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - if [ -d "frontend" ]; then cd frontend && npm install; else echo "Frontend not found"; fi
      - if [ -d "backend" ]; then cd backend && npm install; else echo "Backend not found"; fi
  pre_build:
    commands:
      - echo Pre-build step...
      - ls -la # Debugging files
  build:
    commands:
      - echo Building frontend if it exists...
      - if [ -d "frontend" ]; then cd frontend && npm run build; else echo "Frontend not found"; fi
      - echo Building backend...
      - if [ -d "backend" ]; then cd backend && npm run build; else echo "Backend not found"; fi
  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'
