version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd frontend && npm install
      - cd ../backend && npm install
  pre_build:
    commands:
      - echo Pre-build step...
  build:
    commands:
      - echo Building frontend...
      - ls -la # Debugging step to list files in the current directory
      - cd frontend && npm run build # Build frontend
      - echo Building backend...
      - cd backend && npm run build # Build backend
  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - '**/*'
